{
 "title": "SAS/ESP Log Analysis by Project",
 "tags": [
  "sas-esp",
  "samples"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(memory{namespace=\"$namespace\",project_label!~\"sas_.+\"}, project_label)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connector Status",
   "type": "table",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (connector_name, window) (connector_state{namespace=~\"$namespace\",project=\"$project\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages by Log Level",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\",project=\"$project\",type=\"esp\"} | json | __error__!=\"JSONParserErr\"[$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "Message Totals by Level",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by (namespace,project,level) (count_over_time({namespace=~\"$namespace\",project=\"$project\",type=\"esp\"} | json | __error__ = \"\" | level=~\"INFO|WARN|FATAL|ERROR|SEVERE|\"[$__interval]))",
     "legendFormat": "[ Level : {{level}} ]"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\",project=\"$project\",type=\"esp\"} | json | __error__ = \"\" | line_format \"[{{.level}}\\t] \t {{.message}}\""
    }
   ]
  }
 ]
}