apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: promtail
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: promtail
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
  name: promtail
  namespace: monitoring
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - name: service
    nodePort: 31010
    port: 80
    protocol: TCP
    targetPort: 31010
  selector:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/name: promtail
  sessionAffinity: None
  type: NodePort
