apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: sas-esp-server
    app.kubernetes.io/managed-by: SAS
    heritage: SAS
  name: sas-esp-server
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    path: /SASESP/metrics
    port: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_project]
      targetLabel: project_label
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_annotation_sas_com_tls_enabled_ports]
      action: replace
      regex: all|.*http.*
      targetLabel: __scheme__
      replacement: https
    - sourceLabels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      regex: (https?)
      targetLabel: __scheme__
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      esp-component: project
