{
 "title": "SAS/ESP CPU, Memory and Logs Usage",
 "description": "Sample dashboard for the SAS ESP Operator",
 "tags": [
  "sas-esp",
  "samples"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "loki", "label": "Loki Datasource", "query": "loki" },
   { "name": "prometheus", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "phase",
    "label": "Phase",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=\"$namespace\", pod=\"$pod\"}, phase)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[ Projects ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(esp_project_state{namespace=~\"$namespace\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) by (namespace, project_name)) or vector(0)"
    }
   ]
  },
  {
   "title": "Number of Windows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(esp_connector_state{namespace=~\"$namespace\",window_name!=\"_eventmetering_\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_window_cpu_usage{namespace=~\"$namespace\",window_name!=\"_eventmetering_\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",project_label!=\"sas_event_stream_processing_client_config_server\",mem_type=\"total\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",project_label!=\"sas_event_stream_processing_client_config_server\",mem_type=\"vm\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",project_label!=\"sas_event_stream_processing_client_config_server\",mem_type=\"rss\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "[ Logs ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages by Log Level",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\",project!~\"|sas-.+\",type=\"esp\"} | json | __error__!=\"JSONParserErr\"[$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "Message Totals by Level",
   "type": "barchart",
   "description": "This panel shows the total number of messages per project by log level type. Data might apply to projects that are not currently running.",
   "gridPos": { "h": 14, "w": 13, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (namespace,project,level) (count_over_time({namespace=~\"$namespace\",project!~\"|sas-.+\",type=\"esp\"} | json | __error__ = \"\" | level=~\"INFO|WARN|FATAL|ERROR|SEVERE|\"[$__interval]))",
     "legendFormat": "[ namespace : {{namespace}} / project : {{project}} / Level : {{level}} ]"
    }
   ]
  },
  {
   "title": "Current Projects",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "esp_project_state{namespace=~\"$namespace\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}"
    }
   ]
  },
  {
   "title": "[ CPU ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current CPU Usage by Project",
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(esp_window_cpu_usage{namespace=~\"$namespace\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) by (namespace, project_name, pod)"
    }
   ]
  },
  {
   "title": "CPU Usage by Window",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(esp_window_cpu_usage{namespace=~\"$namespace\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) by (namespace, project_name, window_name)",
     "legendFormat": "[ Namespace: {{namespace}} / Project: {{project_name}} / Window : {{window_name}} ]"
    }
   ]
  },
  {
   "title": "[ Memory ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage - Total",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",mem_type=\"total\",project_label!=\"sas_event_stream_processing_client_config_server\"}) by (namespace, project_label)",
     "legendFormat": "[ Namespace : {{namespace}} / Project: {{project_label}} ]"
    }
   ]
  },
  {
   "title": "Memory Usage - Virtual",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",mem_type=\"vm\",project_label!=\"sas_event_stream_processing_client_config_server\"}) by (namespace, project_label)",
     "legendFormat": "[ Namespace : {{namespace}} / Project: {{project_label}} ]"
    }
   ]
  },
  {
   "title": "Memory Usage - RSS",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",mem_type=\"rss\",project_label!=\"sas_event_stream_processing_client_config_server\"}) by (namespace, project_label)",
     "legendFormat": "[ Namespace : {{namespace}} / Project: {{project_label}} ]"
    }
   ]
  }
 ]
}