{
 "title": "ESP Overview",
 "tags": [
  "esp_overview",
  "esp",
  "sas-esp"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(esp_project_state{namespace=~\"$namespace\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) by (namespace, project_name)) or vector(0)"
    }
   ]
  },
  {
   "title": "Flatlined",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(esp_project_state{namespace=~\"(cert-manager|default|ecr|espfull|ingress-nginx|kube-system|monitoring|nfs-client|twistlock)\", project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"})"
    }
   ]
  },
  {
   "title": "Projects with Connector Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by(project_name) (esp_connector_state{namespace=~\"$namespace\"}) == bool 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Firing Alerts", "type": "alertlist", "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 } },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_window_cpu_usage{namespace=~\"$namespace\",window_name!=\"_eventmetering_\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",project_label!=\"sas_event_stream_processing_client_config_server\",mem_type=\"rss\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\",project_label!=\"sas_event_stream_processing_client_config_server\",mem_type=\"vm\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Running Projects & Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Running Projects",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(esp_window_cpu_usage{namespace=~\"$namespace\",project_name!~\"_meta_|sas_event_stream_processing_client_config_server\", container=~\"(esm|esps).*\"}) by (container, pod, project_name)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", container=~\"(esm|esps).*\", image!=\"\"}) by (container, pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(ceil(increase(kube_pod_container_status_restarts_total{namespace=~'$namespace', container=~\"(esm|esps).*\"}[$__range]) * on(pod) group_left(label_type,label_project) kube_pod_labels{namespace=~'$namespace',label_type='esp', container!=\"\"})) by (pod,container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "group(esp_project_state{namespace=~\"$namespace\", project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) by (project_name, pod, namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\"}[5m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$namespace\", container=~\"(esm|esps).*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(esp_connector_cur_rate{namespace=~\"$namespace\"}) by (project_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by(project_name) (esp_connector_state{namespace=~\"$namespace\"}) == bool 3",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Firing Alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 9, "x": 15, "y": 5 } },
  {
   "title": "Inactive & Flatlined Projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inactive Projects",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "esp_project_state{container!=\"\",instance!=\"\",project_name!~\"(_meta_|sas_event_stream_processing_client_config_server).*\"} == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flatlined Projects",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "group(esp_project_state{namespace=~\"$namespace\", project_name!~\"_meta_|sas_event_stream_processing_client_config_server\"}) by (project_name, pod, namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(esp_connector_cur_rate{namespace=~\"$namespace\"}) by (project_name, pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}