{
 "title": "Project Overview",
 "tags": [
  "project_overview",
  "esp",
  "sas-esp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(esp_project_state{namespace=\"$namespace\", project_name!~\"sas_event_stream_processing_client_config_server|_meta_\"},project_name)"
    }
   },
   {
    "name": "pod",
    "label": "Running Pod",
    "query": {
     "query": "query_result(esp_window_cpu_usage{namespace=~\"$namespace\",project_name=\"$project\"})"
    }
   },
   {
    "name": "selected_connectors",
    "label": "Selected connectors",
    "query": {
     "query": "query_result((esp_connector_state{namespace=~\"$namespace\",project_name=\"$project\"}))"
    }
   },
   {
    "name": "connector_flatline_interval",
    "label": "Connector Flatline Check Interval",
    "query": "30s"
   }
  ]
 },
 "panels": [
  { "title": "Selected Pod Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_project_state{namespace=\"$namespace\", project_name=\"$project\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_window_cpu_usage{namespace=\"$namespace\", project_name=\"$project\",window_name!=\"_eventmetering_\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[$__rate_interval])) by (container) /sum(increase(container_cpu_cfs_periods_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[$__rate_interval])) by (container)",
     "legendFormat": "$project"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(increase(kube_pod_container_status_restarts_total{namespace='espfull'}[$__range]) * on(pod) group_left(label_type,label_project) kube_pod_labels{namespace='espfull',label_type='esp', label_project=\"$project\"} > 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Overview",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", project=\"$project\", type=\"esp\"} | json | __error__ != `JSONParserErr` [$__interval])) by (level)"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\", project_label=\"$project\", mem_type=\"vm\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "RSS Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(esp_mem_usage{namespace=~\"$namespace\", project_label=\"$project\", mem_type=\"rss\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Historical Project Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "esp_project_state{namespace=\"$namespace\", project_name=\"$project\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Connectors and Windows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "All Connectors Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "esp_connector_state{namespace=~\"$namespace\",project_name=\"$project\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(esp_connector_cur_rate{namespace=\"$namespace\", project_name=\"$project\"}) by (connector_name, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 14 } },
  {
   "title": "Selected Connectors Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "esp_connector_state{namespace=~\"$namespace\",project_name=\"$project\", connector_name=~\"$selected_connectors\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(esp_connector_cur_rate{namespace=\"$namespace\", project_name=\"$project\", connector_name=~\"$selected_connectors\"}) by (connector_name, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Window",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(esp_window_cpu_usage{namespace=~\"$namespace\",project_name=\"$project\"}) by (namespace, project_name, window_name)",
     "legendFormat": " {{window_name}}"
    }
   ]
  },
  {
   "title": "Connector Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "esp_connector_cur_rate{namespace=\"$namespace\", project_name=\"$project\"}",
     "legendFormat": "{{connector_name}} ({{pod}})"
    }
   ]
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Connector Flatline History",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "esp_connector_cur_rate{namespace=\"$namespace\", project_name=\"$project\", connector_name=~\"$selected_connectors\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "esp_connector_state{namespace=\"$namespace\", project_name=\"$project\", connector_name=~\"$selected_connectors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) by (pod) * on(pod) group_left(project_name) esp_project_state{project_name=\"$project\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\r\n) by (pod) * on(pod) group_left(project_name) esp_project_state{project_name=\"$project\"}\r\n",
     "legendFormat": "requests ({{pod}})"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\"}\r\n) by (pod) * on(pod) group_left(project_name) esp_project_state{project_name=\"$project\"}\r\n\r\n",
     "legendFormat": "limits ({{pod}})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (container, pod)  * on(pod, container) group_left(project_name) esp_project_state{project_name=\"$project\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\r\n) by (pod) * on(pod) group_left(project_name) esp_project_state{project_name=\"$project\"}",
     "legendFormat": "requests ({{pod}})"
    },
    {
     "expr": "sum(\r\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\"}\r\n) by (pod) * on(pod) group_left(project_name) esp_project_state{project_name=\"$project\"}\r\n",
     "legendFormat": "limits ({{pod}})"
    }
   ]
  }
 ]
}